// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_user_by_email.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, display_name
FROM users
WHERE email = $1
LIMIT 1
`

type GetUserByEmailRow struct {
	ID          uuid.UUID
	Email       string
	Password    string
	DisplayName string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.DisplayName,
	)
	return i, err
}
