// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: mark_setup_complete.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const markSetupCompleted = `-- name: MarkSetupCompleted :exec
UPDATE users
SET 
  preference = $2,
  has_completed_setup = true,
  updated_at = now()
WHERE id = $1
`

type MarkSetupCompletedParams struct {
	ID         uuid.UUID
	Preference json.RawMessage
}

func (q *Queries) MarkSetupCompleted(ctx context.Context, arg MarkSetupCompletedParams) error {
	_, err := q.db.ExecContext(ctx, markSetupCompleted, arg.ID, arg.Preference)
	return err
}
