// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: verify_metadata_ids.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const verifyMetadataIDs = `-- name: VerifyMetadataIDs :one
SELECT NOT EXISTS (
  SELECT 1
  FROM unnest($1::uuid[]) AS input_id
  WHERE NOT EXISTS (
    SELECT 1
    FROM preference_metadata pm
    WHERE pm.id = input_id
  )
) AS all_ids_valid
`

func (q *Queries) VerifyMetadataIDs(ctx context.Context, dollar_1 []uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, verifyMetadataIDs, pq.Array(dollar_1))
	var all_ids_valid bool
	err := row.Scan(&all_ids_valid)
	return all_ids_valid, err
}
