version: "3.7"
services:
  postgres:
    image: postgres:17.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_server
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  db_data:
